// ANGULAR/src/app/components/add-task/add-task.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Task } from '../../Task'

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css']
})
export class AddTaskComponent implements OnInit {

  // Output for event emitter
  @Output() onTaskAdd: EventEmitter<Task> = new EventEmitter;

  // Forms class must contain property for each form input
  text: string;
  day: string;
  reminder: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit() {
    if (this.text == '' || this.day == '') {
      alert('Please enter Task detail')
    } else {
      // New Object
      const newTask = {
        text: this.text,
        day: this.day,
        reminder: this.reminder
      }

      // Lets emit this object
      this.onTaskAdd.emit(newTask);

      // Clear the form
      this.text = '';
      this.day = '';
      this.reminder = false;
    }
  }

}

<!-- mgModel defines 2 way data binding between Form input and Class property -->
<!-- ngSubmit calls a method when form is submit and it override the default submit behaviour
    , so no need to disable it-->
<form class='add-form' (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="text">Task</label>
        <input type="text" name="text" [(ngModel)]="text" id="text" placeholder="Add Task"/>
    </div>
    <div class="form-control">
        <label for="day">Day & Time</label>
        <input type="text" name="day" [(ngModel)]="day" id="day" placeholder="Add Day & Time"/>
    </div>
    <div class="form-control form-control-check">
        <label for="reminder">Set Reminder</label>
        <input type="checkbox" name="reminder" [(ngModel)]="reminder" id="reminder"/>
    </div>
    <input type="submit" value="Save Task" class="btn btn-block">
</form>

// REACT-JS/1-OLD-WITH-CRA/src/components/AddTask.js
//Every Object in our form will have its own state for capturing values
import { useState } from 'react'

const AddTask = ({ onAdd }) => {

    // State for each element
    const [text, setText] = useState('')
    const [day, setDay] = useState('')
    const [reminder, setReminder] = useState(false)

    // We need to make prevent page submit and do some validation, so we need a custom function
    const saveTask = (e) => {
        // Prevent dafault page submit action
        e.preventDefault()

        // validate fields data
        if (!text || !day) {
            alert('Please enter task details')
            return
        }

        onAdd({ text, day, reminder });

        // Reset the form
        setText('');
        setDay('');
        setReminder(false);

    }

    return (
        <form className='add-form' onSubmit={saveTask}>
            <div className='form-control'>
                <label>Task</label>
                <input name='text'
                    type='text'
                    placeholder='Add Task'
                    value={text}
                    onChange={(e) => setText(e.target.value)} />
            </div>
            <div className='form-control'>
                <label>Day and Time</label>
                <input name='day'
                    type='text'
                    placeholder='Add Day and Time'
                    value={day}
                    onChange={(e) => setDay(e.target.value)} />
            </div>
            <div className='form-control form-control-check'>
                <label>Set Reminder</label>
                <input name='reminder'
                    type='checkbox'
                    value={reminder}
                    checked={reminder}
                    onChange={(e) => setReminder(e.currentTarget.checked)} />
            </div>
            <div className='form-control'>
                <input type='submit' value='Save Task' className='btn btn-block' />
            </div>
        </form>
    );
}

export default AddTask
